-- Add quote workflow statuses
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'AWAITING_ADMIN_QUOTE';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'QUOTE_PENDING_CLIENT_APPROVAL';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'QUOTE_APPROVED_AWAITING_PAYMENT';

-- Add quote tracking fields
ALTER TABLE "Application"
ADD COLUMN IF NOT EXISTS "quotedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "quoteApprovedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "quoteVersion" INTEGER NOT NULL DEFAULT 0;
