CREATE TYPE "ClientEntityType" AS ENUM ('PRIVATE_OWNER', 'DECEASED_ESTATE', 'COMPANY_OR_TRUST', 'NON_SA_CITIZEN');

ALTER TABLE "Client"
ADD COLUMN "entityType" "ClientEntityType" NOT NULL DEFAULT 'PRIVATE_OWNER',
ADD COLUMN "referralSource" TEXT;
